#image: node:18.13.0

#cache:
#  paths:
#    - library/node_modules/

#stages:
#  - lint
#  - build
#  - release

#before_script:
#  - npm i -g npm@8.19.3
#  - cd library
#  - npm ci

#lint:
#  stage: lint
#  script:
#    - npm run lint
#  only:
#    - master

#build:
#  stage: build
#  script:
#    - npm run build
#  only:
#    - master

#release:
#  stage: release
#  script:
#    - ['npm version patch -m "chore: release version %s"']
#    - npm publish
#  only:
#    - master
